### ISSUE TITLE
Questions about the parameters of cutout in object detection?

### ISSUE THREAD

**Issue by sky-fly97** [uoguelph-mlrg/Cutout#13]
**In object detection**, I would like to ask how to set the default parameter of cut out better? For example, num_holes and length, I want to know whether you has done any experiments when adding these parameters, or has anyone else set them? Thank you

**Comment by TDeVries** [comment]
I haven't looked into using it for object detection too much, but the random erasing paper does explore this: https://arxiv.org/abs/1708.04896. If you're looking for data augmentation strategies for object detection you might also find this autoaugment variant useful: https://arxiv.org/abs/1906.11172.
