### ISSUE TITLE
Which version of SVHN is used to train?

### ISSUE THREAD

**Issue by QiushiYang** [uoguelph-mlrg/Cutout#15]
Many thanks for your clean codes.

I wonder which version of SVHN dataset (it consists of two sub-versions, one including 73257 training images and 26032 test images, the other one named extra version containing 631131 images) is used to train?

**Comment by TDeVries** [comment]
Hi, we combined and use both subsets. See here: https://github.com/uoguelph-mlrg/Cutout/blob/master/train.py#L120
