### ISSUE TITLE
hi,I have a question about your paper?Could you give me some tips?

### ISSUE THREAD

**Issue by gogo03** [uoguelph-mlrg/Cutout#7]
First,thank you very much,You have done a very good job.
I don't unstand the following content in your paper
Figure 4: Magnitude of feature activations, sorted by descending value, and averaged over all test samples. A standard ResNet18 is compared with a ResNet18 trained with cutout at three different depths.

could your give me some tips how do you generate these figures?
and I don't know the means of the  abscissa and ordinate values.
I need you help.thank you.

**Comment by TDeVries** [comment]
Hello, I've attached an old and messy script that I think was used to create the plots from the paper. You'll have to change the file extension from .txt back to .py if you want to use it. 

In summary, we take the maximum value from each feature map, sort the values in the channel dimension, calculate the average across the batch dimension, and then sort again across channels.

[visualize_activations.txt](https://github.com/uoguelph-mlrg/Cutout/files/3842096/visualize_activations.txt)

**Comment by gogo03** [comment]
thank you very much!
