### ISSUE TITLE
TypeError: 'tuple' object is not callable

### ISSUE THREAD

**Issue by etetteh** [uoguelph-mlrg/Cutout#8]
I am trying to use cutout in my implementation, I keep getting the error below when I run the train code. Please, am I doing something wrong?

**from cutout      import Cutout**

train_transform = transforms.Compose([
    transforms.RandomCrop(32, padding=4, fill=128),
    transforms.RandomHorizontalFlip(),
    CIFAR10Policy(),
    **Cutout(n_holes=1, length=16),**
    transforms.ToTensor(),
    transforms.Normalize((0.4914, 0.4822, 0.4465), (0.2023, 0.1994, 0.2010))
])

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-23-6eaeee21c85e> in <module>
      4     correct = 0.0
      5     total = 0.0
----> 6     for i, data in enumerate(train_loader):
      7         # get the inputs; data is a list of [inputs, labels]
      8         inputs, labels = data

~/anaconda3/lib/python3.7/site-packages/torch/utils/data/dataloader.py in __next__(self)
    817             else:
    818                 del self._task_info[idx]
--> 819                 return self._process_data(data)
    820 
    821     next = __next__  # Python 2 compatibility

~/anaconda3/lib/python3.7/site-packages/torch/utils/data/dataloader.py in _process_data(self, data)
    844         self._try_put_index()
    845         if isinstance(data, ExceptionWrapper):
--> 846             data.reraise()
    847         return data
    848 

~/anaconda3/lib/python3.7/site-packages/torch/_utils.py in reraise(self)
    383             # (https://bugs.python.org/issue2651), so we work around it.
    384             msg = KeyErrorMessage(msg)
--> 385         raise self.exc_type(msg)

TypeError: Caught TypeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/enoch/anaconda3/lib/python3.7/site-packages/torch/utils/data/_utils/worker.py", line 178, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/enoch/anaconda3/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/enoch/anaconda3/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/enoch/anaconda3/lib/python3.7/site-packages/torchvision/datasets/cifar.py", line 125, in __getitem__
    img = self.transform(img)
  File "/home/enoch/anaconda3/lib/python3.7/site-packages/torchvision/transforms/transforms.py", line 61, in __call__
    img = t(img)
  File "/home/enoch/medicals/cutout.py", line 23, in __call__
    h = img.size(1)
TypeError: 'tuple' object is not callable

**Comment by TDeVries** [comment]
That is strange, I have not seen this behaviour before. Will it work if you replace `h = img.size(1)` with` h = img.shape[1]`, and likewise for width?

**Comment by etetteh** [comment]
Well that didn't work either.
These worked: # image has the format (w, h)
h = img.height or img.size[1]
w = img.width or img.size[0]

There were other errors after fixing the previous errors. I did some modifications and finally got a working code. 
I've forked and uploaded the code

**Comment by TDeVries** [comment]
Ah, you're calling Cutout before calling toTensor and Normalize. The original code expects a tensor, but before toTensor the images are in PIL format. Sorry that I did not catch this before.

If applying Cutout before normalization the masked patches will probably be black rather than grey (assuming using a zero mask). I'm not sure whether this will have any effect on the final results, but if you notice a difference in performance than what I've reported, this may be why.

**Comment by etetteh** [comment]
O okay. Thanks for the clarification.
I had to transform to tensor and PIL image, because of the position of
cutout in my code. I think my modification will allow cutout to come before
toTensor and normalize

I also didn't notice it. Never thought the position mattered
